#[riscv_rt::exception]
fn my_exception() {}

fn main() {}
